apiVersion: v1
kind: ConfigMap
metadata:
  name: yitam-config
  namespace: yitam
data:
  NODE_ENV: "production"
  PORT: "3000"
  CLIENT_URL: "https://yitam.org"
  MCP_SERVER_PATH: "/app/mcp/core/server/yitam-tools.js"
  VITE_SERVER_URL: "https://yitam.org"
  VITE_GOOGLE_CLIENT_ID: "1027650180838-6ora2sdrjre213ujv9hjah4m8mu3v8ju.apps.googleusercontent.com"
  # Other environment variables from prod.env should be added here
  # or preferably in a Secret for sensitive information 