version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: yitam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 100mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: yitam-redis-commander
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  yitam-mcp:
    build:
      context: ../yitam-mcp
      dockerfile: Dockerfile
    volumes:
      - yitam-mcp-dist:/app/dist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - yitam-mcp-dist:/app/mcp:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_URL=https://yitam.org
      - MCP_SERVER_PATH=/app/mcp/core/server/yitam-tools.js
      - REDIS_URL=redis://redis:6379
    env_file:
      - prod.env
    depends_on:
      - yitam-mcp
      - redis
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=https://yitam.org
        - VITE_GOOGLE_CLIENT_ID=1027650180838-6ora2sdrjre213ujv9hjah4m8mu3v8ju.apps.googleusercontent.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/conf.d/blacklist.conf:/etc/nginx/conf.d/blacklist.conf:ro
      - ./ssl/yitam.org.crt:/etc/nginx/ssl/yitam.org.crt:ro
      - ./ssl/yitam.org.key:/etc/nginx/ssl/yitam.org.key:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  yitam-mcp-dist: