version: '3.8'

services:
  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: "postgres://postgres:unleash@db/unleash"
      DATABASE_SSL: "false"
      UNLEASH_URL: "http://localhost:4242"
      INIT_ADMIN_API_TOKENS: "default:development.unleash-insecure-api-token"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-client-token"
    depends_on:
      - db
    command: >
      sh -c "
        /wait-for-it.sh db:5432 -t 60 &&
        node index.js"
    networks:
      - unleash-network

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: unleash
      POSTGRES_USER: postgres
      POSTGRES_DB: unleash
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - unleash-network

networks:
  unleash-network:
    driver: bridge 