version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_URL=https://yitam.org
      - MCP_SERVER_PATH=/app/mcp/core/server/yitam-tools.js
    ports:
      - "3000:3000"
    volumes:
      - ./server/.env:/app/.env:ro
      - ../yitam-mcp/dist:/app/mcp:ro
      - ../yitam-mcp/.env:/app/mcp/.env:ro
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_SERVER_URL=https://yitam.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
    restart: unless-stopped 