version: '3.8'

services:
  yitam-mcp:
    build:
      context: ../yitam-mcp
      dockerfile: Dockerfile
    volumes:
      - yitam-mcp-dist:/app/dist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - yitam-mcp-dist:/app/mcp:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_URL=https://yitam.org
      - MCP_SERVER_PATH=/app/mcp/core/server/yitam-tools.js
    depends_on:
      - yitam-mcp
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=https://yitam.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/conf.d/blacklist.conf:/etc/nginx/conf.d/blacklist.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - server
    restart: unless-stopped

volumes:
  yitam-mcp-dist: 