version: '3.8'

services:
  yitam-mcp:
    build:
      context: ../yitam-mcp
      dockerfile: Dockerfile
    volumes:
      - yitam-mcp-dist:/app/dist

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - yitam-mcp-dist:/app/mcp:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CLIENT_URL=https://yitam.org
      - MCP_SERVER_PATH=/app/mcp/core/server/yitam-tools.js
    env_file:
      - prod.env
    depends_on:
      - yitam-mcp
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=https://yitam.org
        - VITE_GOOGLE_CLIENT_ID=1027650180838-6ora2sdrjre213ujv9hjah4m8mu3v8ju.apps.googleusercontent.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/conf.d/blacklist.conf:/etc/nginx/conf.d/blacklist.conf:ro
      - ./ssl/yitam.org.crt:/etc/nginx/ssl/yitam.org.crt:ro
      - ./ssl/yitam.org.key:/etc/nginx/ssl/yitam.org.key:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
    restart: unless-stopped

volumes:
  yitam-mcp-dist: 