apiVersion: v1
kind: Secret
metadata:
  name: ssl-certs
  namespace: yitam
type: Opaque
data:
  # These would need to be replaced with the actual base64-encoded certificate and key
  # Use: cat /path/to/cert.pem | base64 -w 0
  yitam.org.crt: "" # Replace with base64-encoded certificate
  yitam.org.key: "" # Replace with base64-encoded private key 