name: Test

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install server dependencies
      working-directory: ./server
      run: npm ci
      
    - name: Run server tests
      working-directory: ./server
      run: npm test
      
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci
      
    - name: Run client tests
      working-directory: ./client
      run: npm test 